server:
    port: ${PORT:8081}
spring:
    application:
        name: product-api
    datasource:
        initialization-mode: always
        jpa:
            hibernate:
                ddl-auto: create-drop
            show-sql: true
        password: ${PRODUCT_DB_PASSWORD:product_password}
        url: jdbc:postgresql://localhost:5433/product_db
        username: ${PRODUCT_DB_USER:postgres}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create-drop # so developers can create the database test
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    sql:
        init:
            mode: always

app-config:
    secrets:
        api-secret: ${API_SECRET:YXV0aC1hcGktc2VjcmV0LWRldi0xMjM0NTY=}